### ISSUE TITLE
SERIALIZER

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client-demo#6]
If we receive an xml request, is it possible to use the serializer only with xsd? without metadata and wsdl?

Like: $ this-> serializer-> deserialize ((string) $ request-> getRawBody (), $ class, 'xml');

Thanks for advance

**Comment by goetas** [comment]
no, metadata are fundamental. 
maybe http://php.net/manual/en/function.simplexml-load-string.php is what you need...?

**Comment by victorgp89** [comment]
Yes, 
But you have an example of how to create metadata only with xsd.

Something like this:
"scripts": {
    "build": "xsd2php convert:php '/var/www/synergy/synergyserver/include/ota/OTA_HotelAvail*.xsd' --ns-map='http://www.opentravel.org/OTA/2003/05;Igm/Synergy/Models/OTA1/2007B/' --ns-dest='Igm/Synergy/Models/OTA1/2007B/;src/Mercurio/OTA/V2007B'"
  }



I'm returning an error of this type:
 **There are no commands defined in the "convert" namespace.**

**Comment by goetas** [comment]
metadata can be created from xsd or from wsdl

**Comment by victorgp89** [comment]
Yes for sure, 

That's why I generated the following config.yml.

![image](https://user-images.githubusercontent.com/9083812/33946108-3230c01a-e021-11e7-8e19-af7a9f1f190e.png)


Execute: vendor/bin/xsd2php convert config/test.yml /var/www/igm_client/include/ota/OTA_HotelResRQ.xsd

![image](https://user-images.githubusercontent.com/9083812/33946157-5214fff4-e021-11e7-955c-969137a4b17a.png)

But I've this issue:   **Unable to determine location to save PHP class 'Mercurio\OTA\2007B\AcceptablePaymentCardsInfoType'**  

I don't understand why.

**Comment by victorgp89** [comment]
Sorry, It's my fault.
Linux use back slash \. So sorry.

**Comment by goetas** [comment]
ok, then closing
