### ISSUE TITLE
Characters

### ISSUE THREAD

**Issue by victorgp89** [goetas-webservices/soap-client-demo#7]
Dear, 

May I know what is : <**ns-77e106cb**:OTA_HotelAvailNotifRQ xmlns:ns-**77e106cb**?

I don't understand how these symbols are formed.

Thank you.

**Comment by goetas** [comment]
see here https://en.wikipedia.org/wiki/XML_namespace#Namespace_declaration what namespace prefixes. this one is just randomly generated. for XML semantics has no meaning

**Comment by victorgp89** [comment]
Is it possible to remove these namespaces?

2018-04-04 10:01 GMT+02:00 Asmir Mustafic <notifications@github.com>:

**Comment by victorgp89** [comment]
Because some consumers of the api have problems processing it


2018-04-09 12:47 GMT+02:00 Victor Galvez Pages <victorgp.18@gmail.com>:

**Comment by goetas** [comment]
Unfortunately is not that easy. (Means that the consumer is not properly
xml compliant
